### ISSUE TITLE
Upload Image page CSS enhancement

### ISSUE THREAD

**Issue by shreyakapoor08** [CropAi/Frontend#144] opened 2020-04-13 17:02 UTC
- **I'm submitting an enhancement

  - [x] bug report
  - [ ] feature request

- **Do you want to request a feature or report a bug?** 
Enhancement

- **What is the current behavior?**
1. The heading is a normal text
2. One button has hover effect and other does not have
![image](https://user-images.githubusercontent.com/31164665/79141035-a13fae80-7dd6-11ea-99c2-f6e5c31a1fa9.png)

- **What is the expected behavior?**
1. It should be bold
2. CSS improvement of button

**Comment by shreyakapoor08** [comment] 2020-04-13 17:04
@rajats98 Can I work on it ?

**Comment by rajats98** [comment] 2020-04-13 17:14
Hello Shreya, 
Although we are not taking design enhancement issues (until there is a bug caused by design) right now, But since this is the first time you are contributing to this repo, I am allowing this :) 
@shreyakapoor08  Assigning this to you!

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by shreyakapoor08** [comment] 2020-04-13 17:16
@rajats98 Hello ☺
Okay, I will take care of it from next time. ☺
Thank you

**Comment by rajats98** [comment] 2020-04-15 10:47
@shreyakapoor08 Submit it by tomorrow morning and make sure you pull the latest code. Lots of changes are made in this section

**Closed as completed** 2020-04-15 16:44 UTC
Labels: gssoc20, beginner
