### ISSUE TITLE
Landing Page 3 Bug

### ISSUE THREAD

**Issue by Satyam3976** [CropAi/Frontend#136] opened 2020-04-12 11:01 UTC
The page will redirect to analyze crop only when the arrow is clicked not when start analysing section is clicked. It's a bit confusing... We should not keep things so narrow and confusing for the user, maybe the user thinks that the button is not working. 
PS- When I am working on the issue, I also thought that why the button is not working and will get to know the reason after watching the code.

**Comment by rajats98** [comment] 2020-04-12 12:21
Duplicate of issue #116

**Closed as completed by rajats98** 2020-04-12 12:21 UTC
Labels: duplicate
